#!/bin/bash
# Audit script using Codex CLI
# https://developers.openai.com/codex/noninteractive/
#
# Usage:
#   ./scripts/audit-codex.sh              # Full audit (6 checks)
#   ./scripts/audit-codex.sh --quick      # Quick review uncommitted changes
#   ./scripts/audit-codex.sh --custom "Check for X"  # Custom query
#   ./scripts/audit-codex.sh --json       # Output as JSON

set -e

MODE="${1:-full}"
CUSTOM_QUERY="${2:-}"

OUTPUT_DIR=".audit"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="${OUTPUT_DIR}/audit_${TIMESTAMP}.md"

mkdir -p "$OUTPUT_DIR"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}Codex Audit Script${NC}"
echo ""

# Quick review of uncommitted changes
if [ "$MODE" == "--quick" ] || [ "$MODE" == "-q" ]; then
  echo -e "${CYAN}Reviewing uncommitted changes...${NC}"
  codex exec "Review the uncommitted changes in this repo. Focus on: type safety, null handling, error cases. List file:line for each issue found. Be concise."
  exit 0
fi

# Custom query
if [ "$MODE" == "--custom" ] || [ "$MODE" == "-c" ]; then
  if [ -z "$CUSTOM_QUERY" ]; then
    echo "Usage: $0 --custom \"Your question here\""
    exit 1
  fi
  echo -e "${CYAN}Running custom query...${NC}"
  codex exec "$CUSTOM_QUERY"
  exit 0
fi

# JSON mode for CI
if [ "$MODE" == "--json" ]; then
  echo '{"audit_start": "'$(date -Iseconds)'", "checks": ['
  FIRST=true

  QUERIES=(
    "Find type mismatches in src/: nullable fields used as non-nullable. List file:line."
    "Find BigInt precision issues in src/: Number() on bigint, mixed arithmetic. List file:line."
    "Find null safety bugs in src/: accessing properties on possibly null. List file:line."
  )

  for QUERY in "${QUERIES[@]}"; do
    if [ "$FIRST" = true ]; then
      FIRST=false
    else
      echo ","
    fi
    codex exec --json "$QUERY" 2>/dev/null | jq -c '{query: "'"$QUERY"'", result: .}'
  done

  echo ']}'
  exit 0
fi

# Full audit
echo "# Codex Audit Report" > "$REPORT_FILE"
echo "Date: $(date)" >> "$REPORT_FILE"
echo "Directory: $(pwd)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Ordered array for consistent execution
CATEGORIES=(
  "Type Safety"
  "BigInt Handling"
  "Null Safety"
  "Error Handling"
  "Async Issues"
  "Schema Sync"
)

declare -A QUERIES
QUERIES["Type Safety"]="Analyze src/ for type mismatches: nullable fields accessed as non-nullable, incorrect type assertions, missing type guards. List each issue as file:line - description."
QUERIES["BigInt Handling"]="Analyze src/ for BigInt issues: precision loss from Number() on bigint, missing BigInt() conversions, arithmetic mixing bigint and number. List each issue as file:line - description."
QUERIES["Null Safety"]="Analyze src/ for null/undefined bugs: accessing properties on possibly null values without checks, optional chaining missing. List each issue as file:line - description."
QUERIES["Error Handling"]="Analyze src/ for error handling issues: empty catch blocks, swallowed errors, missing error propagation, untyped catch. List each issue as file:line - description."
QUERIES["Async Issues"]="Analyze src/ for async bugs: missing await, floating promises, potential race conditions, unhandled rejections. List each issue as file:line - description."
QUERIES["Schema Sync"]="Compare IndexedFeedback interface in src/core/indexer-client.ts with the Supabase feedbacks table schema. Check if all columns are represented with correct types (especially value, value_decimals, score nullable)."

TOTAL=${#CATEGORIES[@]}
CURRENT=0

for CATEGORY in "${CATEGORIES[@]}"; do
  QUERY="${QUERIES[$CATEGORY]}"
  ((CURRENT++))

  echo -e "${YELLOW}[$CURRENT/$TOTAL]${NC} $CATEGORY..."

  echo "## $CATEGORY" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"

  # Run codex exec and capture output
  # Using -o to write final message, stderr shows progress
  TEMP_OUT=$(mktemp)
  if codex exec "$QUERY" -o "$TEMP_OUT" 2>/dev/null; then
    RESULT=$(cat "$TEMP_OUT")
  else
    RESULT="No issues found or error occurred."
  fi
  rm -f "$TEMP_OUT"

  echo "$RESULT" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "---" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"

  # Rate limit protection
  sleep 2
done

echo "" >> "$REPORT_FILE"
echo "_Generated by audit-codex.sh_" >> "$REPORT_FILE"

echo ""
echo -e "${GREEN}Audit complete!${NC}"
echo "Report saved: $REPORT_FILE"
echo ""
echo "Preview (first 30 lines):"
echo "─────────────────────────"
head -30 "$REPORT_FILE"
